//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.33440.
// 


namespace fb2.Model
{
    using fb2.Model.Data;
    using fb2.Model.Description;

    [XmlType(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
    [XmlRoot(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IsNullable=false)]
    public class FictionBook {
        /// <remarks/>
        [XmlElement("stylesheet")]
        public FictionBookStylesheet[] stylesheet { get; set; }

        /// <remarks/>
        [XmlElement("description")]
        public FictionBookDescription description { get; set; }

        /// <remarks/>
        [XmlElement("body")]
        public FictionBookBody[] body { get; set; }

        /// <remarks/>
        [XmlElement("binary")]
        public FictionBookBinary[] binary { get; set; }
    }
}