//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.0.30319.33440.
// 


namespace fb2.Model
{
    using fb2.Model.Description;

    [XmlType(AnonymousType=true, Namespace="http://www.gribuser.ru/xml/fictionbook/2.0")]
    [XmlRoot(Namespace="http://www.gribuser.ru/xml/fictionbook/2.0", IsNullable=false)]
    public class FictionBook {
    
        private FictionBookStylesheet[] stylesheetField;
    
        private FictionBookDescription descriptionField;
    
        private FictionBookBody[] bodyField;
    
        private FictionBookBinary[] binaryField;
    
        /// <remarks/>
        [XmlElement("stylesheet")]
        public FictionBookStylesheet[] stylesheet {
            get {
                return this.stylesheetField;
            }
            set {
                this.stylesheetField = value;
            }
        }
    
        /// <remarks/>
        public FictionBookDescription description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("body")]
        public FictionBookBody[] body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
    
        /// <remarks/>
        [XmlElement("binary")]
        public FictionBookBinary[] binary {
            get {
                return this.binaryField;
            }
            set {
                this.binaryField = value;
            }
        }
    }
}